In [71]:
import time
import matplotlib.pyplot as plt
import numpy as np
import data_loader as dl
import scdd as sd
import scipy as sp

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [72]:
data,X,p0_true,size_factor = dl.load_toy_ann_data()
print('True mean')
print(np.mean(X,axis=0))
print('True cov')
print(np.cov(X.T))
print('True PC')
print(np.corrcoef(X.T))

True mean
[0.305989   0.19048567 0.50352533]
True cov
[[ 0.07213833 -0.03138634 -0.04075199]
 [-0.03138634  0.06067881 -0.02929246]
 [-0.04075199 -0.02929246  0.07004445]]
True PC
[[ 1.         -0.47439398 -0.57329596]
 [-0.47439398  1.         -0.44931458]
 [-0.57329596 -0.44931458  1.        ]]


In [78]:
mean_dd,cov_dd,PC_dd  = sd.dd_covariance(data,size_factor=size_factor)
mean_ml,cov_ml,PC_ml  = sd.ml_covariance(data,size_factor=size_factor)
M_ml,M_dd = sd.dd_1d_moment(data,size_factor=size_factor)
Nc,G = data.shape
Nr = data.X.sum()/Nc

#time start: 0.0s
n_cell=100000, n_gene=3, Nr=20.0
#total: 0.04s
#time start: 0.0s
n_cell=100000, n_gene=3, Nr=20.0
#total: 0.02s
#time start: 0.0s
n_cell=100000, n_gene=3
#total: 0.01s


In [79]:
print('dd mean')
print(mean_dd/Nr)
print(M_dd[0]/Nr)
print('dd cov')
print(cov_dd/Nr)
print((M_dd[1]-M_dd[0]**2)/Nr)
print('dd PC')
print(PC_dd)

dd mean
[0.3057686  0.19015255 0.50328346]
[0.3057686  0.19015255 0.50328346]
dd cov
[[ 1.44088718 -0.62622825 -0.81830304]
 [-0.62622825  1.20976939 -0.58123237]
 [-0.81830304 -0.58123237  1.40489912]]
[1.44088718 1.20976939 1.40489912]
dd PC
[[ 1.         -0.47431447 -0.57514401]
 [-0.47431447  1.         -0.44583681]
 [-0.57514401 -0.44583681  1.        ]]


In [80]:
print('ml mean')
print(mean_ml/Nr)
print(M_ml[0]/Nr)
print('ml cov')
print(cov_ml/Nr)
print((M_ml[1]-M_ml[0]**2)/Nr)
print('ml PC')
print(PC_ml)

ml mean
[0.3057686  0.19015255 0.50328346]
[0.3057686  0.19015255 0.50328346]
ml cov
[[ 1.7598504  -0.62622825 -0.81830304]
 [-0.62622825  1.40802153 -0.58123237]
 [-0.81830304 -0.58123237  1.93021727]]
[1.7598504  1.40802153 1.93021727]
ml PC
[[ 1.         -0.39782323 -0.44399   ]
 [-0.39782323  1.         -0.35256731]
 [-0.44399    -0.35256731  1.        ]]


In [81]:
Nr = data.X.sum()/data.shape[0]
Y = data.X.todense()
Y_sf = (Y.T/size_factor).T
print('mean')
print(Y_sf.mean(axis=0)/Nr)
print('cov')
print(np.cov(Y_sf.T)/Nr**2)
print('PC')
print(np.corrcoef(Y_sf.T))


mean
[[0.3057686  0.19015255 0.50328346]]
cov
[[ 0.08787411 -0.03126928 -0.04086009]
 [-0.03126928  0.07030634 -0.02902251]
 [-0.04086009 -0.02902251  0.09638099]]
PC
[[ 1.         -0.39782323 -0.44399   ]
 [-0.39782323  1.         -0.35256731]
 [-0.44399    -0.35256731  1.        ]]
