In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pandas as pd
import h5py
import os
import time

from util import *
from data_loader import * 
import scdd as sd

%matplotlib inline
%load_ext autoreload
%autoreload 2

/home/martin/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
## import data 
data = load_10x_2k()
sc.pp.filter_genes(data,min_counts=20*data.shape[0])
data.shape

Variable names are not unique. To make them unique, call `.var_names_make_unique`.


(2022, 35)

In [17]:
sub_data_0 = sd.subsample_anndata(data,5,5,random_seed=0)
sub_data_1 = sd.subsample_anndata(data,5,5,random_seed=1)

#time start: 0.0s
before cell subsamp (2022, 35)
after cell subsamp (5, 35)
#time sub-sample cells: 0.0042s
#time sub-sample counts: 0.0112s

#time start: 0.0s
before cell subsamp (2022, 35)
after cell subsamp (5, 35)
#time sub-sample cells: 0.0025s
#time sub-sample counts: 0.0074s



In [18]:
sub_data_0.X[0,:].todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
sub_data_1.X[0,:].todense()

matrix([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.random.choice(5, 3)

array([1, 3, 2])

In [59]:
sc.pp.subsample

<function scanpy.preprocessing.simple.subsample>